FROM python:3

WORKDIR /webscraper

COPY . .

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir -r requirements.txt

RUN pip install -U pip setuptools wheel
RUN pip install -U spacy
RUN python -m spacy download en_core_web_sm

CMD ["python", "-m", "src.distributed.master", "--urls", "https://www.dlsu.edu.ph", "--port", "5672" "--time", "10", "--batch-size", "5"]
