FROM python:3

WORKDIR /webscraper

COPY . .

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir -r requirements.txt

RUN pip install -U pip setuptools wheel
RUN pip install -U spacy
RUN python -m spacy download en_core_web_sm

ENTRYPOINT ["python", "-m", "src.distributed.worker"]
CMD ["python", "-m", "src.distributed.worker", "--host", "localhost", "--port", "5000", "--sub-nodes", "3"]
